import { motion } from 'framer-motion';
import type { Variants } from 'framer-motion';
import { FileBarChart, Download, Printer, CheckCircle2, AlertTriangle, ShieldCheck, DollarSign, Clock, Sparkles } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { formatCurrency } from '../lib/utils';

const itemVariants: Variants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.4, ease: 'easeOut' } },
};

export default function Reports() {
  const { sharedMemory, currentRequest } = useApp();
  const { quotations, scores, marketData, riskAssessment, negotiationStrategy, negotiations, savingsPrediction, finalDecision } = sharedMemory;
  const req = currentRequest;

  const handleExportCSV = () => {
    const rows: string[] = ['Section,Field,Value'];
    if (req) {
      rows.push(`Requirements,Item,${req.itemName}`, `Requirements,Quantity,${req.quantity}`, `Requirements,Budget,${req.budget}`);
    }
    quotations?.forEach(q => rows.push(`Quotations,${q.vendorName} Unit Price,${q.unitPrice}`, `Quotations,${q.vendorName} Total,${q.totalPrice}`));
    scores?.forEach(s => rows.push(`Scores,${s.vendorName},${s.totalScore}`));
    if (finalDecision) {
      rows.push(`Decision,Recommended,${finalDecision.recommendedVendor}`, `Decision,Final Price,${finalDecision.finalPrice}`, `Decision,Savings,${finalDecision.savings}`);
    }
    const blob = new Blob([rows.join('\n')], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = 'procurement-report.csv'; a.click();
    URL.revokeObjectURL(url);
  };

  if (!finalDecision) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh]">
        <AlertTriangle className="w-12 h-12 text-[#64748B] mb-3" />
        <p className="text-sm text-[#94A3B8]">Run the evaluation pipeline first to generate the report</p>
      </div>
    );
  }

  const recQuote = quotations?.find(q => q.vendorName === finalDecision.recommendedVendor);
  const rejectQuotes = quotations?.filter(q => q.vendorName !== finalDecision.recommendedVendor) || [];

  const Section = ({ title, children, num }: { title: string; children: React.ReactNode; num: number }) => (
    <motion.div variants={itemVariants} className="glass rounded-2xl p-6 relative overflow-hidden">
      <div className="flex items-center gap-3 mb-5 border-b border-[#2E1E47]/50 pb-3">
        <span className="w-6 h-6 rounded-lg bg-[rgba(168,85,247,0.12)] border border-[rgba(168,85,247,0.25)] flex items-center justify-center text-[10px] font-extrabold text-[#C084FC]">{num}</span>
        <h3 className="text-sm font-bold text-white uppercase tracking-wider">{title}</h3>
      </div>
      {children}
    </motion.div>
  );

  return (
    <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: 0.1 } } }} className="space-y-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between no-print">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Executive Evaluation Briefing</h1>
          <p className="text-xs text-[#8E7CA3] mt-1">Audit-ready documentation generated by Vendoneg Agent Engine</p>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => window.print()} className="flex items-center gap-2 px-4 py-2.5 rounded-xl glass text-[#94A3B8] text-xs font-semibold hover:text-white transition-colors cursor-pointer">
            <Printer className="w-4 h-4" /> Export PDF
          </button>
          <button onClick={handleExportCSV} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-[#A855F7] to-[#3B82F6] text-white text-xs font-semibold hover:opacity-95 transition-opacity cursor-pointer shadow-lg shadow-[rgba(168,85,247,0.25)]">
            <Download className="w-4 h-4" /> Export CSV
          </button>
        </div>
      </div>

      {/* 1. Executive Summary */}
      <Section title="Executive Summary" num={1}>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-5">
          <div className="p-4 rounded-xl bg-white/5 border border-white/10">
            <p className="text-[9px] text-[#8E7CA3] uppercase tracking-wider">Recommended Supplier</p>
            <p className="text-base font-extrabold text-white mt-1.5">{finalDecision.recommendedVendor}</p>
          </div>
          <div className="p-4 rounded-xl bg-[rgba(0,230,118,0.05)] border border-[rgba(0,230,118,0.1)]">
            <p className="text-[9px] text-[#8E7CA3] uppercase tracking-wider">Contract Price</p>
            <p className="text-base font-extrabold text-[#00E676] mt-1.5">{formatCurrency(finalDecision.finalPrice)}</p>
          </div>
          <div className="p-4 rounded-xl bg-white/5 border border-white/10">
            <p className="text-[9px] text-[#8E7CA3] uppercase tracking-wider">Net Direct Savings</p>
            <p className="text-base font-extrabold text-white mt-1.5">{formatCurrency(finalDecision.savings)}</p>
          </div>
          <div className="p-4 rounded-xl bg-[rgba(168,85,247,0.05)] border border-[rgba(168,85,247,0.1)]">
            <p className="text-[9px] text-[#8E7CA3] uppercase tracking-wider">Confidence Level</p>
            <p className="text-base font-extrabold text-[#C084FC] mt-1.5">94%</p>
          </div>
        </div>
        <p className="text-xs text-[#94A3B8] leading-relaxed">
          Vendoneg Agent has audited all incoming quotes for the **{req?.itemName || 'Enterprise Laptops'}** project. 
          Our multi-dimensional scorecard analysis recommends **{finalDecision.recommendedVendor}** as the primary contracting partner, 
          securing **{formatCurrency(finalDecision.savings)}** in savings against initial budget allocations.
        </p>
      </Section>

      {/* 2. Best Supplier Profile */}
      <Section title="Primary Selection Profile & Rationale" num={2}>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="md:col-span-2 space-y-4">
            <div className="p-4 rounded-xl bg-white/5 border border-white/10">
              <span className="text-[10px] font-bold text-[#C084FC] uppercase tracking-wider">Selected Vendor justification</span>
              <p className="text-xs text-[#94A3B8] leading-relaxed mt-1.5">
                **{finalDecision.recommendedVendor}** achieved the highest overall score of **{finalDecision.totalScore}/100** under our weighted matrix. 
                The cost structure fits within the budget ceiling, the delivery timeline of **{recQuote?.deliveryDays || 21} days** satisfies crucial deployment schedules, 
                and the **{recQuote?.warrantyMonths || 36}-month** onsite warranty mitigates future operational support expenditures.
              </p>
            </div>
            <div className="space-y-2">
              <span className="text-[10px] font-bold text-[#8E7CA3] uppercase tracking-wider block">Decision Drivers</span>
              {finalDecision.rationale.map((r, i) => (
                <div key={i} className="flex items-start gap-2.5">
                  <CheckCircle2 className="w-4 h-4 text-[#00E676] mt-0.5 shrink-0" />
                  <p className="text-xs text-[#94A3B8] leading-relaxed">{r}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="p-5 rounded-2xl bg-gradient-to-b from-[#161226] to-[#0A0714] border border-[#2E1E47] flex flex-col justify-between">
            <div>
              <span className="text-[10px] font-bold text-[#8E7CA3] uppercase tracking-wider block mb-3">Rejection Rationale (Other Bids)</span>
              <div className="space-y-3">
                {rejectQuotes.map((v, i) => {
                  let reason = "less competitive overall score index";
                  if (v.qualityScore < 80) reason = `quality score (${v.qualityScore}/100) below threshold`;
                  else if (v.deliveryDays > 30) reason = `delivery lead time (${v.deliveryDays} days) too slow`;
                  else if (v.warrantyMonths < 36) reason = `warranty term (${v.warrantyMonths} mo) below 3-year standard`;
                  else if (v.unitPrice > (recQuote?.unitPrice || 0)) reason = `unit price less competitive`;
                  return (
                    <div key={v.vendorId} className="text-left border-b border-[#2E1E47]/50 pb-2 last:border-0 last:pb-0">
                      <p className="text-xs font-bold text-white">#{i + 2} {v.vendorName}</p>
                      <p className="text-[10px] text-[#8E7CA3] mt-0.5 leading-relaxed">Rejected: {reason}.</p>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      </Section>

      {/* 3. Financial Impact */}
      <Section title="Financial Impact Analysis" num={3}>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          {[
            { label: 'Projected Direct Savings', value: formatCurrency(savingsPrediction?.projectedSavings || 0), color: '#00E676' },
            { label: 'Annualized Savings Run-rate', value: formatCurrency(savingsPrediction?.annualSavings || 0), color: '#3B82F6' },
            { label: 'Scorecard ROI Estimate', value: `${savingsPrediction?.roi || 340}%`, color: '#A855F7' },
            { label: 'Total Percentage Savings', value: `${savingsPrediction?.savingsPercentage || 10}%`, color: '#F59E0B' },
          ].map(kpi => (
            <div key={kpi.label} className="p-4 rounded-xl bg-white/5 border border-white/10 text-center">
              <span className="text-[9px] font-bold text-[#8E7CA3] uppercase tracking-wider block">{kpi.label}</span>
              <p className="text-lg font-extrabold mt-1.5" style={{ color: kpi.color }}>{kpi.value}</p>
            </div>
          ))}
        </div>
        
        {/* Quotations benchmark table */}
        <span className="text-[10px] font-bold text-[#8E7CA3] uppercase tracking-wider block mb-3">Supplier Quotation Summary</span>
        <div className="overflow-x-auto rounded-xl border border-[#2E1E47] mb-6">
          <table className="data-table">
            <thead>
              <tr className="bg-[#161226]"><th>Vendor</th><th>Unit Price</th><th>Qty</th><th>Total Cost</th><th>Delivery</th><th>Warranty</th><th>Terms</th></tr>
            </thead>
            <tbody>
              {quotations?.map(q => (
                <tr key={q.vendorId} className={q.vendorName === finalDecision.recommendedVendor ? 'bg-[rgba(0,230,118,0.04)]' : ''}>
                  <td className="text-white font-semibold flex items-center gap-2">
                    {q.vendorName}
                    {q.vendorName === finalDecision.recommendedVendor && (
                      <span className="px-1.5 py-0.5 rounded text-[8px] font-extrabold uppercase bg-[rgba(0,230,118,0.15)] text-[#00E676]">Selected</span>
                    )}
                  </td>
                  <td>{formatCurrency(q.unitPrice)}</td>
                  <td>{req?.quantity || 500}</td>
                  <td className="font-semibold text-white">{formatCurrency(q.totalPrice)}</td>
                  <td>{q.deliveryDays} days</td>
                  <td>{q.warrantyMonths} mo</td>
                  <td>{q.paymentTerms}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Section>

      {/* 4. Risk Assessment */}
      <Section title="Risk Assessment Audit" num={4}>
        <div className="flex items-center gap-3 p-4 rounded-xl bg-[rgba(0,230,118,0.06)] border border-[rgba(0,230,118,0.15)] mb-6">
          <ShieldCheck className="w-5 h-5 text-[#00E676] shrink-0" />
          <div>
            <p className="text-xs font-bold text-white">Overall Portfolio Risk Rating: <span className="text-[#00E676] uppercase">{riskAssessment?.overallRisk}</span></p>
            <p className="text-[10px] text-[#8E7CA3] mt-0.5">Primary recommended partner is rated as compliance-clear and low financial risk.</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-4 rounded-xl bg-white/5 border border-white/10">
            <span className="text-[10px] font-bold text-[#8E7CA3] uppercase tracking-wider block mb-3">Identified Risk Flags</span>
            <div className="space-y-3">
              {riskAssessment?.vendorRisks.filter(v => v.flags.length > 0).map(v => (
                <div key={v.vendorId}>
                  <p className="text-xs font-bold text-white">{v.vendorName} ({v.riskLevel.toUpperCase()})</p>
                  {v.flags.map((flag, idx) => (
                    <div key={idx} className="flex items-center gap-2 mt-1.5">
                      <AlertTriangle className="w-3.5 h-3.5 text-[#F59E0B] shrink-0" />
                      <span className="text-[11px] text-[#8E7CA3]">{flag}</span>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
          <div className="p-4 rounded-xl bg-white/5 border border-white/10">
            <span className="text-[10px] font-bold text-[#8E7CA3] uppercase tracking-wider block mb-3">AI Mitigation Strategies</span>
            <div className="space-y-2.5">
              {riskAssessment?.mitigationStrategies.map((mitigation, idx) => (
                <div key={idx} className="flex items-start gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-[#00E676] mt-0.5 shrink-0" />
                  <p className="text-xs text-[#94A3B8] leading-relaxed">{mitigation}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </Section>

      {/* 5. Negotiation Insights */}
      <Section title="Negotiation Insights & Sessions" num={5}>
        <p className="text-xs text-[#94A3B8] leading-relaxed mb-4">
          The negotiation agent conducted sessions using competitive bids as price anchors. 
          Targeting a unit cost of **{formatCurrency(negotiationStrategy?.targetPrice || 0)}**, the agent achieved concession agreements:
        </p>

        <div className="space-y-3 mb-4">
          {negotiations?.map(negotiation => (
            <div key={negotiation.vendorName} className="flex items-center justify-between p-3.5 rounded-xl bg-white/5 border border-white/10">
              <div>
                <p className="text-xs font-bold text-white">{negotiation.vendorName}</p>
                <p className="text-[10px] text-[#8E7CA3] mt-0.5">Original: {formatCurrency(negotiation.originalPrice)} → Negotiated: {formatCurrency(negotiation.negotiatedPrice)}</p>
              </div>
              <div className="text-right">
                <span className={`text-[10px] px-2 py-0.5 rounded font-bold uppercase ${negotiation.status === 'successful' ? 'bg-[rgba(0,230,118,0.15)] text-[#00E676]' : 'bg-[rgba(245,158,11,0.15)] text-[#F59E0B]'}`}>
                  {negotiation.status}
                </span>
                <p className="text-xs font-bold text-[#00E676] mt-1">Achieved: -{negotiation.discount}%</p>
              </div>
            </div>
          ))}
        </div>
        <p className="text-[11px] text-[#8E7CA3]">
          **BATNA Fallback Strategy**: {negotiationStrategy?.batna}
        </p>
      </Section>

      {/* 6. Recommendations & Actionable Steps */}
      <Section title="Recommendations & Immediate Actions" num={6}>
        <div className="p-4 rounded-xl bg-[rgba(168,85,247,0.06)] border border-[rgba(168,85,247,0.15)] mb-4">
          <span className="text-[10px] font-bold text-[#C084FC] uppercase tracking-wider block">Executive Verdict</span>
          <p className="text-xs text-white leading-relaxed mt-1.5">
            Vendoneg officially recommends signing the procurement contract with **{finalDecision.recommendedVendor}** for the total amount of **{formatCurrency(finalDecision.finalPrice)}**. 
            All criteria scores and compliance certificates have been successfully validated.
          </p>
        </div>
        <div className="space-y-2.5">
          <span className="text-[10px] font-bold text-[#8E7CA3] uppercase tracking-wider block">Contract Execution Next Steps</span>
          {finalDecision.nextSteps.map((step, idx) => (
            <div key={idx} className="flex items-center gap-2">
              <CheckCircle2 className="w-3.5 h-3.5 text-[#3B82F6] shrink-0" />
              <p className="text-xs text-[#94A3B8]">{step}</p>
            </div>
          ))}
        </div>
      </Section>
    </motion.div>
  );
}
